'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.join(__dirname,'..'),core=fs.readFileSync(path.join(root,'app-3994-458293-part-b1.js'),'utf8');
// Execute production declarations/functions. No copied isolation implementation.
function declaration(name){
 const m=new RegExp('\\b(?:const|let) '+name+'\\b','m').exec(core);if(!m)throw Error('Declaration: '+name);
 for(let end=core.indexOf(';',m.index);end>=0;end=core.indexOf(';',end+1)){
  const text=core.slice(m.index,end+1);try{new vm.Script(text);return text;}catch(_){if(text.length>50000)throw Error('Declaration too long: '+name);}
 }
}
function fn(name,source=core){
 const m=new RegExp('^(?:async )?function '+name+'\\(','m').exec(source);if(!m)throw Error('Function: '+name);
 const first=source.indexOf('\n',m.index),line=source.slice(m.index,first);
 if(line.endsWith('}'))return line;
 for(let end=source.indexOf('\n}',m.index);end>=0;end=source.indexOf('\n}',end+2)){const text=source.slice(m.index,end+2);try{new vm.Script(text);return text;}catch(_){if(text.length>80000)throw Error('Function parse: '+name);}}
 throw Error(name);
}
const stateNames=['progress','schoolPreferences','schoolCompare','schoolPartnerDraft','errorReplay','cloudReady','accountEnrollment','missionSystem','aiInstructor','instructorPortal','schoolPortal','zeroErrorState','examDayState','recoveryState','coachState','onboarding','privacyPreferences','pilotAnalytics','schoolDashboard','personalRoadmap','lptvPassport','userProfile','countryPackEngineState','licensePackEngineState','languageTwin','realRoadTwin','realRoadTelemetryStore','mdmProductionPermissionState','mdmProductionSyncState','schoolOperationsProductionState','securityTrustState'];
const otherNames=['settings','quiz','bridgeState','flashState','timerId','mdmLearningSyncState','mdmServerMissions','mdmSchoolStudentMissions','mdmServerRoster','mdmPlatformOwnerGate','mdmProtectedContentStatus','mdmSchoolAdminConsole','mdmPortableSyncState','mdmLearningSyncInFlight','mdmServerRosterInFlight','mdmProductionSyncInFlight','mdmSchoolAdminInFlight','mdmEnrollmentInFlight','mdmPortableSyncInFlight','mdmPlatformOwnerGateInFlight','mdmProtectedContentInFlight','mdmPortableSyncApplying','mdmPortableSyncTimer','instructorStudioObjectUrls','realRoadTelemetryRuntime','mdmAuthSession','mdmAuthGeneration','mdmAuthInFlight','mdmAuthRefreshInFlight'];
const functionNames=['clone','load','save','createRegistrationId','normaliseAiRecoveryPlan','mdmAccountOwnData','mdmAccountRehydrateData','instructorStudioClearObjectUrls','realRoadTelemetryDetach','schoolOperationsDefault','schoolOperationsLoad','schoolOperationsSave','fleetCorporateDefault','fleetCorporateLoad','fleetCorporateSave','mdmDataRpc','mdmDataErrorMessage','mdmPortableSyncMeta','mdmPortableSyncMetaSave','mdmPortableSyncMarkDirty','mdmPortableSnapshotItems','mdmPortablePayload','mdmPortablePayloadValid','mdmPortableStudyScore','mdmPortableParseRaw','mdmPortableApplyPayload','mdmPortableServerPull','mdmPortableServerPush','mdmPortableSyncReconcile','mdmPortableSyncForceRestore','mdmPortableSyncForceUpload','mdmStudentRefreshMissions','mdmSchoolRefreshStudentMissions','schoolRosterRefreshServer','mdmServerRosterReset','schoolOperationsProductionProbe','schoolOperationsProductionResetForAccount','schoolOperationsProductionAuthScope','schoolOperationsProductionSave','mdmProductionSyncPullPreview','mdmProductionSyncSave','mdmProductionSyncClone','mdmProductionSyncEntity','mdmProductionSyncRecordKey','mdmProductionSyncKey','mdmProductionSyncMergeServerVersions','mdmEnsureFreshAuthForData','mdmAuthParse','mdmAuthIsCurrent','mdmAuthAdvanceGeneration','mdmAuthBeginSession','mdmAuthSave','mdmAuthStoreResponse','mdmAuthFresh','mdmAuthSummary','mdmAuthClear','instructorStudioOpenDb','instructorStudioMediaGet','instructorStudioMediaPut','instructorStudioMediaDelete','importBackup'];
// Functions not used by a test can remain unresolved until called; missing
// functions in this list are removed only when they are genuinely absent.
const productionFunctions=functionNames.filter(n=>new RegExp('^(?:async )?function '+n+'\\(','m').test(core)).map(n=>fn(n)).join('\n');
const declarations=new Map();
function addDecl(name){if(declarations.has(name))return;const text=declaration(name);declarations.set(name,null);
 for(const id of new Set(text.match(/\b[A-Z][A-Z0-9_]+\b/g)||[])){if(id!==name&&new RegExp('\\b(?:const|let) '+id+'\\b','m').test(core))addDecl(id);}
 declarations.set(name,text);
}
for(const n of [...stateNames,...otherNames,'MDM_PORTABLE_SYNC_KEYS','MDM_PORTABLE_SYNC_META_KEY','MDM_PORTABLE_SYNC_SCHEMA','SCHOOL_OPERATIONS_KEY','FLEET_CORPORATE_KEY','INSTRUCTOR_STUDIO_DB','INSTRUCTOR_STUDIO_STORE','SCHOOL_DEMOS'])addDecl(n);
// Declare constants first, then the production lexical state in source order.
const constants=[...declarations].filter(([n])=>!stateNames.includes(n)&&!otherNames.includes(n)).map(([,s])=>s).join('\n');
const variables=[...stateNames,...otherNames].sort((a,b)=>core.indexOf(declaration(a))-core.indexOf(declaration(b))).map(n=>declaration(n)).join('\n');
const startupSource=productionFunctions+'\n'+[...new Set(declarations.values())].sort((a,b)=>core.indexOf(a)-core.indexOf(b)).join('\n');
const AUTH='mdm_auth_session_v4410',SCHOOL='mdm_school_operations_45824',FLEET='mdm_fleet_corporate_45825',CACHE='mdm-school-evidence-cache-v1';
const session=(id,generation=1)=>({status:'authenticated',generation,user:{id,email:id.toLowerCase()+'@example.test'},accessToken:'access-'+id,refreshToken:'refresh-'+id,expiresAt:Date.now()+3600000});
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};};
async function tick(){for(let i=0;i<5;i++)await Promise.resolve();}
function harness(seed={},initial='A'){
 class Storage{constructor(){this.data=new Map();}getItem(k){return this.data.has(String(k))?this.data.get(String(k)):null;}setItem(k,v){this.data.set(String(k),String(v));}removeItem(k){this.data.delete(String(k));}key(i){return [...this.data.keys()][i]||null;}get length(){return this.data.size;}clear(){this.data.clear();}}
 const local=new Storage(),sessionStore=new Storage();for(const[k,v]of Object.entries(seed))local.setItem(k,typeof v==='string'?v:JSON.stringify(v));if(initial)local.setItem(AUTH,JSON.stringify(session(initial)));
 const events=new Map(),requests=[],fetches=[],timers=[],clearedTimers=[],readers=[],dbOpens=[];
 const element=()=>({querySelector:()=>null,querySelectorAll:()=>[],classList:{add(){},remove(){},contains(){return false;}},remove(){},addEventListener(){}});
 const context={console,AbortController,URLSearchParams,history:{pushState(){},replaceState(){}},Storage,localStorage:local,sessionStorage:sessionStore,URL:{revokeObjectURL(){}},Blob,Date,Math,JSON,Set,WeakMap,WeakSet,Promise,TextEncoder,Uint8Array,ArrayBuffer,location:{href:'https://example.test/#home',hash:'#home',hostname:'localhost',reload(){throw Error('Unexpected reload');}},navigator:{geolocation:{clearWatch(){}}},document:{getElementById:()=>null,querySelector:()=>null,querySelectorAll:()=>[],addEventListener(){},createElement:element,head:{appendChild(){}},body:element()},setTimeout:(f,ms)=>{timers.push({f,ms});return timers.length;},clearTimeout(id){clearedTimers.push(id);if(timers[id-1])timers[id-1].cancelled=true;},setInterval:(f,ms)=>{timers.push({f,ms});return timers.length;},clearInterval(){},addEventListener:(n,f)=>{if(!events.has(n))events.set(n,[]);events.get(n).push(f);},removeEventListener(){},MDM_BACKEND_CONFIG:{enabled:true,endpoint:'https://example.test',publishableKey:'test-public-key'},BUILD_VERSION:'test-build',C:{},Q:[],screen:element(),toast(){},render(){},t:k=>k,lang3:(it,en)=>en,confirm:()=>true,FileReader:class{constructor(){readers.push(this);}readAsText(){}},XMLHttpRequest:class{constructor(){this.status=0;this.responseText='';this.headers={};requests.push(this);}open(method,url){this.method=method;this.url=url;}setRequestHeader(k,v){this.headers[k]=v;}send(body){this.body=body;}},fetch:(url,options)=>{const d=deferred();fetches.push({url,options,...d});return d.promise;},indexedDB:{open(name){const req={};dbOpens.push({name,req});return req;}}};
 context.window=context;vm.createContext(context);
 vm.runInContext(fs.readFileSync(path.join(root,'mdm-account-isolation-safe-45831532.js'),'utf8'),context);
 vm.runInContext(startupSource,context);
 vm.runInContext("function accountEnrollmentBindToAuthUser(){};function mdmBackendPublicConfig(){return window.MDM_BACKEND_CONFIG;} window.MDM_ACCOUNT_ISOLATION_SAFE.subscribe(mdmAccountRehydrateData);",context);
 const api=context.MDM_ACCOUNT_ISOLATION_SAFE;
 return {context,api,local,sessionStore,requests,fetches,timers,clearedTimers,readers,dbOpens,eval:code=>vm.runInContext(code,context),login(id){context.nextUser=id;vm.runInContext("{const nextGen=mdmAuthBeginSession(nextUser.toLowerCase()+'@example.test');mdmAuthStoreResponse({access_token:'access-'+nextUser,refresh_token:'refresh-'+nextUser,expires_in:3600,user:{id:nextUser,email:nextUser.toLowerCase()+'@example.test'}},'',nextGen);}",context);},logout(){vm.runInContext('mdmAuthClear();',context);},respond(index,body,status=200){const r=requests[index];assert.ok(r,'Expected actual RPC request');r.status=status;r.responseText=JSON.stringify(body);r.onload();},module(file){vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'),context);}};
}
function write(h,k,v){h.context.testValue=v;h.context.testKey=k;return h.eval('save(testKey,testValue)');}
function read(h,k){return JSON.parse(h.local.getItem(k)||'null');}
for(const [name,transition]of [['A logout B',h=>{h.logout();h.login('B');}],['A B without reload',h=>h.login('B')]])test('ISO-01 '+name+': School/Fleet isolated; B can write its own namespace',()=>{const h=harness();write(h,SCHOOL,{bookings:[{id:'booking-A'}]});write(h,FLEET,{context:{organisation:'fleet-A'}});transition(h);assert.equal(read(h,SCHOOL),null);assert.equal(read(h,FLEET),null);write(h,SCHOOL,{bookings:[{id:'booking-B'}]});assert.equal(read(h,SCHOOL).bookings[0].id,'booking-B');assert.match(h.local.data.get(SCHOOL+'::user:A'),/booking-A/);});
test('A B A: each account retains its own data and old operations remain invalid',()=>{const h=harness();write(h,FLEET,{context:{organisation:'fleet-A'}});const owner=h.api.capture();h.login('B');write(h,FLEET,{context:{organisation:'fleet-B'}});h.login('A');assert.equal(read(h,FLEET).context.organisation,'fleet-A');assert.equal(h.api.isCurrent(owner),false);});
test('New login to same account restores owned data but invalidates previous operation',()=>{const h=harness();write(h,SCHOOL,{bookings:[{id:'mine'}]});const owner=h.api.capture();h.logout();h.login('A');assert.equal(read(h,SCHOOL).bookings[0].id,'mine');assert.equal(h.api.isCurrent(owner),false);});
test('Memory: progress/profile and server caches are synchronously rehydrated without reload',()=>{const h=harness({'mdm-v1-user-profile::user:B':{firstName:'B'},'mdm-v1-progress::user:B':{seen:{B:true}}});h.eval("progress.seen.A=true;userProfile.firstName='A';mdmServerRoster.students=[{email:'a-private@example.test'}];");h.login('B');assert.equal(h.eval('userProfile.firstName'),'B');assert.deepEqual(JSON.parse(h.eval('JSON.stringify(progress.seen)')),{B:true});assert.equal(h.eval('mdmServerRoster.students.length'),0);});
test('Memory: saving old School/Fleet objects and fresh containers with old nested data is rejected',()=>{const h=harness();write(h,SCHOOL,{bookings:[{id:'A'}]});write(h,FLEET,{context:{organisation:'A'}});h.eval('var oldSchool=schoolOperationsLoad();var oldFleet=fleetCorporateLoad();');h.login('B');assert.equal(h.eval('save(SCHOOL_OPERATIONS_KEY,oldSchool)'),false);assert.equal(h.eval('save(FLEET_CORPORATE_KEY,oldFleet)'),false);assert.equal(h.eval('save(SCHOOL_OPERATIONS_KEY,{bookings:oldSchool.bookings})'),false);assert.equal(read(h,SCHOOL),null);assert.equal(read(h,FLEET),null);});
test('Late School response after B does not publish A roster or overwrite B in-flight state',async()=>{const h=harness();const p=h.eval('schoolRosterRefreshServer({silent:true})');await tick();h.login('B');h.eval('mdmServerRosterInFlight=true;');h.respond(0,{authorized:true,school_id:'school-A',students:[{name:'A-student'}]});assert.equal(await p,false);assert.equal(h.eval('mdmServerRoster.students.length'),0);assert.equal(h.eval('mdmServerRosterInFlight'),true);});
test('Switch during the first Auth await prevents an A operation sending a request as B',async()=>{const h=harness();const p=h.eval("mdmSchoolRefreshStudentMissions('A-student')");h.login('B');assert.equal(await p,false);assert.equal(h.requests.length,0);});
test('ISO-03 late evidence/mission fetch does not cache A missions under B',async()=>{const h=harness();h.module('mdm-student-school-evidence-45838239.js');const p=h.context.MDM_STUDENT_SCHOOL_EVIDENCE_45838239_API.load();h.login('B');h.fetches[0].resolve({ok:true,text:async()=>JSON.stringify({missions:[{id:'A-mission',status:'assigned',payload:{lifecycle:'unified_mission_v1'}}]})});assert.equal(await p,false);assert.equal(read(h,CACHE),null);assert.equal(h.local.data.get(CACHE+'::user:B'),undefined);});
test('ISO-02 portable B payload excludes every account namespace previously written by A',()=>{const h=harness();h.eval("for(const key of MDM_PORTABLE_SYNC_KEYS)if(key!=='mdm-v1-settings')save(key,{privateOwner:'A-private'});save('mdm-v1-settings',{lang:'it',theme:'dark'});");h.login('B');const payload=h.eval('JSON.stringify(mdmPortablePayload())');assert.ok(!payload.includes('A-private'));assert.equal(read(h,'mdm-v1-settings').lang,'it');});
module.exports={harness,fn,deferred,tick,read,write,core,AUTH,SCHOOL,FLEET,CACHE};

test('Fleet: late server preview cannot publish A corporate records in B memory/cache',async()=>{const h=harness();h.eval('mdmProductionSyncState.schemaReady=true;');const p=h.eval('mdmProductionSyncPullPreview({silent:true})');await tick();h.login('B');h.respond(0,{ok:true,items:[{entity_type:'fleet_corporate',local_id:'current',payload:{context:{organisation:'A-private'}}}]});assert.equal(await p,false);assert.ok(!h.eval('JSON.stringify(mdmProductionSyncState)').includes('A-private'));assert.equal(read(h,'mdm-production-sync-v45828'),null);});
test('School Operations: late permissions/snapshot response cannot be saved for B',async()=>{const h=harness();const p=h.eval('schoolOperationsProductionProbe({silent:true})');await tick();h.login('B');h.respond(0,{ok:true,schema_version:'45.8.28.5',can_read:true,can_write:true,server_counts:{crm:99}});assert.equal(await p,false);assert.equal(h.eval('schoolOperationsProductionState.accountUserId'),'');assert.equal(read(h,'mdm-school-operations-production-v458285'),null);});
test('Portable: late A pull cannot restore data or mark the B namespace synchronized',async()=>{const h=harness();const p=h.eval('mdmPortableSyncReconcile({silent:true})');await tick();h.login('B');h.respond(0,{ok:true,found:true,payload:{schema:'mdm-portable-state-v1',items:{[FLEET]:JSON.stringify({context:{organisation:'A-private'}})}},updated_at:'A-server-time'});assert.equal(await p,false);assert.equal(read(h,FLEET),null);assert.equal(read(h,'mdm_portable_sync_v4583135'),null);assert.equal(h.eval('mdmPortableSyncState.status'),'idle');});
test('Portable: response resolved just before B login cannot retry an A upload with B credentials',async()=>{const h=harness();const p=h.eval('mdmPortableServerPush()');h.respond(0,{message:'JWT expired'},401);h.login('B');assert.equal(await p,false);assert.equal(h.requests.length,1);});
test('Portable: an explicitly retained old payload cannot be applied by B',()=>{const h=harness();write(h,FLEET,{context:{organisation:'A-private'}});h.eval('var oldPayload=mdmPortablePayload();');h.login('B');assert.equal(h.eval('mdmPortableApplyPayload(oldPayload)'),false);assert.equal(read(h,FLEET),null);});
test('Evidence: switch while reading the response body also discards A missions',async()=>{const h=harness();h.module('mdm-student-school-evidence-45838239.js');const body=deferred();const p=h.context.MDM_STUDENT_SCHOOL_EVIDENCE_45838239_API.load();h.fetches[0].resolve({ok:true,text:()=>body.promise});await tick();h.login('B');body.resolve(JSON.stringify({missions:[{id:'A-private'}]}));assert.equal(await p,false);assert.equal(read(h,CACHE),null);});
test('Evidence: a valid current-account response remains usable and is hidden after switching',async()=>{const h=harness();h.module('mdm-student-school-evidence-45838239.js');const api=h.context.MDM_STUDENT_SCHOOL_EVIDENCE_45838239_API,p=api.load();h.fetches[0].resolve({ok:true,text:async()=>JSON.stringify({missions:[{id:'A-mission',status:'assigned',payload:{lifecycle:'unified_mission_v1'}}]})});assert.equal(await p,true);assert.equal(api.currentMission().id,'A-mission');h.login('B');assert.equal(api.currentMission(),null);});
test('Legacy: legitimate profile-owned personal history remains recoverable for its owner only',()=>{const seed={'mdm-v1-user-profile':{email:'a@example.test',firstName:'A'},'mdm-v1-progress':{seen:{legacyA:true},correct:{legacyA:2}}};const h=harness(seed);assert.equal(read(h,'mdm-v1-progress').correct.legacyA,2);assert.equal(h.eval('userProfile.firstName'),'A');h.login('B');assert.equal(read(h,'mdm-v1-progress'),null);assert.deepEqual(JSON.parse(h.local.data.get('mdm-v1-progress')),seed['mdm-v1-progress']);h.login('A');assert.equal(read(h,'mdm-v1-progress').correct.legacyA,2);});
for(const key of [SCHOOL,FLEET])test('Legacy identified root owner: '+key,()=>{const h=harness({[key]:{ownerUserId:'A',context:{organisation:'legacy-A'},bookings:[{id:'A'}]}});assert.equal(read(h,key).ownerUserId,'A');h.login('B');assert.equal(read(h,key),null);assert.match(h.local.data.get(key),/legacy-A/);});
test('Legacy: a nested learner/contact email cannot claim an unowned School/Fleet namespace',()=>{const h=harness({'mdm-v1-user-profile':{email:'b@example.test'},[SCHOOL]:{bookings:[{email:'b@example.test',private:'A-private'}]},[FLEET]:{context:{email:'b@example.test',organisation:'A-private'}}},'B');assert.equal(read(h,SCHOOL),null);assert.equal(read(h,FLEET),null);assert.match(h.local.data.get(SCHOOL),/A-private/);});
test('Legacy: explicit foreign UID wins over matching root email',()=>{const h=harness({[FLEET]:{ownerUserId:'A',accountEmail:'b@example.test',context:{organisation:'A'}}},'B');assert.equal(read(h,FLEET),null);});
test('Legacy: existing UID-scoped evidence and School/Fleet data remain accessible only to that UID',()=>{const h=harness({[CACHE+'::user:A']:{missions:[{id:'legacy-mission',student_user_id:'A'}]},[SCHOOL+'::user:A']:{bookings:[{id:'legacy-A'}]}});assert.equal(read(h,CACHE).missions[0].id,'legacy-mission');h.login('B');assert.equal(h.local.getItem(CACHE+'::user:A'),null);assert.equal(h.local.getItem(SCHOOL+'::user:A'),null);h.login('A');assert.equal(read(h,SCHOOL).bookings[0].id,'legacy-A');});
test('Invite: pre-login context and per-invite marker survive logout and account changes',()=>{const invite={token:'invite-context-token',email:'b@example.test'},marker='mdm_invite_email_blank_once_v1::123';const h=harness({'mdm_pilot_pending_invite_v1':invite},null);h.sessionStore.setItem(marker,'1');h.login('A');h.logout();h.login('B');assert.deepEqual(read(h,'mdm_pilot_pending_invite_v1'),invite);assert.equal(h.sessionStore.getItem(marker),'1');});
for(const key of ['mdm-v1-settings','mdm_pilot_device_token_v4583146','mdm_backend_setup_v4400','mdm_auth_attempt_guard_v458319'])test('Device-owned data stays device-owned: '+key,()=>{const h=harness({[key]:{lang:'it',theme:'dark',device:'same-device'}});assert.equal(h.api.classify(key),'device');h.login('B');assert.equal(read(h,key).device,'same-device');assert.equal(h.local.data.has(key+'::user:B'),false);});
test('sessionStorage mission launch is account-owned, not an invite/device context',()=>{const h=harness();const key='mdm-v1-real-road-telemetry-mission-launch';h.sessionStore.setItem(key,JSON.stringify({missionId:'A-mission'}));h.login('B');assert.equal(h.sessionStore.getItem(key),null);h.login('A');assert.equal(JSON.parse(h.sessionStore.getItem(key)).missionId,'A-mission');});
test('Explicit foreign user/owner namespaces, nested mission suffixes and enrollment keys are blocked',()=>{const keys=[FLEET+'::user:A',FLEET+'::owner:A',CACHE+'::user:A','mdm-unified-mission-baseline-v1::user:A::mission-1','mdm-v1-account-enrollment-user:A','mdm_pilot_quality_metrics_v1::A'];const h=harness(Object.fromEntries(keys.map(k=>[k,{private:'A'}])),'B');for(const k of keys){assert.equal(h.local.getItem(k),null,k);h.local.setItem(k,'B-overwrite');assert.match(h.local.data.get(k),/A/,k);h.local.removeItem(k);assert.ok(h.local.data.has(k),k);}});
test('Unknown MDM data is private by default; guests are not promoted into a later account',()=>{const h=harness();write(h,'mdm-new-account-data-v1',{private:'A'});h.logout();assert.equal(read(h,'mdm-new-account-data-v1'),null);h.local.setItem('mdm-new-account-data-v1','guest-data');h.login('B');assert.equal(read(h,'mdm-new-account-data-v1'),null);assert.equal(h.local.data.has('mdm-new-account-data-v1::guest'),false);});
test('Expired credentials alone do not drop ownership; a same-generation refresh keeps current data operations valid',()=>{const h=harness();write(h,FLEET,{context:{organisation:'A'}});const owner=h.api.capture(),s=session('A');s.expiresAt=1;h.local.setItem(AUTH,JSON.stringify(s));assert.equal(h.api.isCurrent(owner),true);assert.equal(read(h,FLEET).context.organisation,'A');s.expiresAt=Date.now()+3600000;s.accessToken='refreshed-A';h.local.setItem(AUTH,JSON.stringify(s));assert.equal(h.api.isCurrent(owner),true);});
test('Bound callback and cloned object preserve A provenance through A B A',()=>{const h=harness();write(h,FLEET,{context:{organisation:'A'}});h.eval('var held=fleetCorporateLoad();');let called=0;const cb=h.api.bind(()=>called++);cb();h.login('B');h.login('A');cb();assert.equal(called,1);assert.equal(h.eval('save(FLEET_CORPORATE_KEY,clone(held))'),false);});
test('Late FileReader import does not overwrite B memory or prepare A data for sync',()=>{const h=harness();h.eval('importBackup({})');const reader=h.readers[0];reader.result=JSON.stringify({progress:{seen:{A:true},correct:{},wrong:{},exams:[]},userProfile:{email:'a@example.test'}});h.login('B');reader.onload();assert.equal(h.eval('progress.seen.A'),undefined);assert.ok(!h.eval('JSON.stringify(mdmPortablePayload())').includes('a@example.test'));});
test('IndexedDB media opens an account namespace and discards an old database-open completion',async()=>{const h=harness();const p=h.eval('instructorStudioOpenDb()');assert.equal(h.dbOpens[0].name,'mdm_instructor_studio_media_v1::user:A');h.login('B');let closed=false;h.dbOpens[0].req.result={close(){closed=true;}};h.dbOpens[0].req.onsuccess();await assert.rejects(p,{code:'MDM_ACCOUNT_CHANGED'});assert.equal(closed,true);});

test('Previously misfiled ISO-03 cache is preserved but cannot be read under B without provenance',()=>{const key=CACHE+'::user:B',h=harness({[key]:{missions:[{id:'A-private',payload:{title:'A-private'}}]}},'B');assert.equal(read(h,CACHE),null);assert.match(h.local.data.get(key),/A-private/);});
test('Cache with an explicitly foreign student is rejected even if filed/stamped as B',()=>{const h=harness({[CACHE+'::user:B']:{ownerUserId:'B',ownershipSchema:'mdm-account-owned-v2',missions:[{id:'A-private',student_user_id:'A'}]}},'B');assert.equal(read(h,CACHE),null);});
test('An object first saved by A cannot later be relabelled/saved by B',()=>{const h=harness();h.eval("var firstSaved={context:{organisation:'A-private'}};save(FLEET_CORPORATE_KEY,firstSaved);");h.login('B');assert.equal(h.eval('save(FLEET_CORPORATE_KEY,firstSaved)'),false);assert.equal(read(h,FLEET),null);});
test('A successful current-account School response still updates its roster',async()=>{const h=harness();const p=h.eval('schoolRosterRefreshServer({silent:true})');await tick();h.respond(0,{ok:true,authorized:true,school_id:'school-A',students:[{name:'my-student'}]});assert.equal(await p,true);assert.equal(h.eval('mdmServerRoster.students[0].name'),'my-student');});
test('Temporary data transport failure retains account data and a following request succeeds',async()=>{const h=harness();write(h,FLEET,{context:{organisation:'A'}});const p=h.eval('schoolRosterRefreshServer({silent:true})');await tick();h.requests[0].ontimeout();assert.equal(await p,false);assert.equal(read(h,FLEET).context.organisation,'A');const next=h.eval('schoolRosterRefreshServer({silent:true})');await tick();h.respond(1,{authorized:true,students:[{name:'recovered'}]});assert.equal(await next,true);});
test('Legitimate backup with matching profile provenance is recovered after B to A without reload',()=>{const prefix='mdm_dennis_pre_rehydrate_v1::old::',suffix='::user:legacy-user';const h=harness({[prefix+'mdm-v1-user-profile'+suffix]:{email:'a@example.test',firstName:'Recovered A'},[prefix+'mdm-v1-progress'+suffix]:{seen:{myHistory:true}}},'B');h.login('A');assert.equal(h.eval('userProfile.firstName'),'Recovered A');assert.equal(h.eval('progress.seen.myHistory'),true);});
test('Storage identity and private Auth token mismatch cannot send a data request',async()=>{const h=harness();h.local.setItem(AUTH,JSON.stringify(session('B',9)));const r=await h.eval("mdmDataRpc('mdm_production_list_own',{})");assert.equal(r.kind,'account');assert.equal(h.requests.length,0);});
test('Old XHR receipt also hides A response after resolution but before inspection',async()=>{const h=harness();const p=h.eval("mdmDataRpc('mdm_school_list_active_students',{})");h.respond(0,{students:[{name:'A-private'}]});const r=await p;h.login('B');assert.equal(r.body,'');assert.equal(r.kind,'account');assert.equal(r.status,0);});
test('Old server portable payload cannot be reapplied after a later account switch',async()=>{const h=harness();const p=h.eval('mdmPortableServerPull()');h.respond(0,{ok:true,found:true,payload:{schema:'mdm-portable-state-v1',items:{[FLEET]:JSON.stringify({context:{organisation:'A-private'}})}}});const old=await p;h.context.retainedServerPayload=old.payload;h.login('B');assert.equal(h.eval('mdmPortableApplyPayload(retainedServerPayload)'),false);assert.equal(read(h,FLEET),null);});
test('P1 remains open: clean nonempty local data still follows the existing checked/synced branch',async()=>{const localProgress={seen:{localA:1},correct:{localA:1},wrong:{},exams:[]},h=harness({'mdm-v1-progress::user:A':localProgress,'mdm_portable_sync_v4583135::user:A':{dirty:false,lastServerUpdatedAt:'older'}});const p=h.eval('mdmPortableSyncReconcile({silent:true})');await tick();h.respond(0,{ok:true,found:true,updated_at:'newer',payload:{schema:'mdm-portable-state-v1',items:{'mdm-v1-progress':JSON.stringify({seen:{serverNew:1},correct:{serverNew:1},wrong:{},exams:[]})}}});assert.equal(await p,true);assert.equal(h.eval('mdmPortableSyncState.status'),'synced');assert.equal(h.eval('progress.seen.serverNew'),undefined);assert.equal(read(h,'mdm_portable_sync_v4583135').lastServerUpdatedAt,'newer');});

test('School invitation queue: a late response cannot refill B account memory',async()=>{const h=harness();const body={innerHTML:'',querySelectorAll:()=>[]},panel={querySelector:()=>body};h.context.document.getElementById=id=>id==='mdmPilotActivationQueuePanel'?panel:null;h.module('mdm-pilot-school-dashboard-4583147.js');const api=h.context.MDM_PILOT_SCHOOL_DASHBOARD_BRIDGE,p=api.refreshActivationQueue();await tick();assert.ok(h.fetches[0]);h.login('B');h.fetches[0].resolve({ok:true,text:async()=>JSON.stringify({authorized:true,items:[{invite_email:'a-private@example.test'}]})});assert.equal(await p,false);assert.equal(api.getState().activationQueue.length,0);assert.equal(api.getState().lastInvitation,null);});
test('School activation alert: the old request cannot use its rows after account change',async()=>{const h=harness();h.context.document.readyState='loading';h.module('mdm-pwa-refresh-458344.js');const p=h.context.MDM_PWA_REFRESH_FIX.refreshSchoolAlert();h.login('B');h.fetches[0].resolve({ok:true,text:async()=>JSON.stringify([{invite_email:'a-private@example.test'}])});assert.equal(await p,false);});
test('Telemetry: a late student mission response cannot save A sessions in B storage',async()=>{const h=harness();h.module('mdm-school-telemetry-engine-45838193.js');const p=h.context.MDM_SCHOOL_TELEMETRY_4583819.sync();h.login('B');assert.ok(h.fetches[0]);h.fetches[0].resolve({ok:true,text:async()=>JSON.stringify({missions:[{id:'A',payload:{schema:'mdm-school-telemetry-evidence-v1',telemetry:{sessionId:'A-private',valid:true}}}]})});assert.equal(await p,false);assert.equal(read(h,'mdm-v1-real-road-telemetry'),null);});
test('Assignment confirmation: A cannot start another retry request with B credentials',async()=>{const h=harness();h.module('mdm-assignment-delivery-integrity-458382531.js');const p=h.context.MDM_ASSIGNMENT_DELIVERY_INTEGRITY_458382531.confirmed('student-A','mission-A');h.login('B');h.fetches[0].resolve({ok:true,status:200,text:async()=>JSON.stringify({missions:[{mission_id:'mission-A'}]})});assert.equal(await p,false);assert.equal(h.fetches.length,1);});
for(const switchBefore of [false,true])test('IndexedDB media result '+(switchBefore?'late after B is discarded':'for A is usable and keeps provenance'),async()=>{const h=harness();const p=h.eval("instructorStudioMediaGet('media-A')");const req={},tx={objectStore:()=>({get:()=>req})};h.dbOpens[0].req.result={transaction:()=>tx,close(){}};h.dbOpens[0].req.onsuccess();await tick();if(switchBefore)h.login('B');req.result={id:'media-A',blob:new Blob(['A-private'])};req.onsuccess();tx.oncomplete();const result=await p;if(switchBefore)assert.equal(result,false);else{assert.equal(result.id,'media-A');assert.equal(h.api.usable(result),true);h.login('B');assert.equal(h.api.usable(result),false);}});
test('A backup explicitly identifying a foreign owner cannot overwrite B progress',()=>{const h=harness({},'B');h.eval('importBackup({})');const reader=h.readers[0];reader.result=JSON.stringify({ownerUserId:'A',progress:{seen:{A:true},correct:{},wrong:{},exams:[]},userProfile:{email:'a@example.test'}});reader.onload();assert.equal(h.eval('progress.seen.A'),undefined);});

for(const result of ['success','network rejection','timeout'])test('RPC timer cleanup: stale '+result+' releases its timer without cancelling B request',async()=>{
 const h=harness();h.context.document.readyState='loading';h.module('mdm-pwa-refresh-458344.js');
 const api=h.context.MDM_PWA_REFRESH_FIX,p=api.refreshSchoolAlert(),old=h.fetches[0],oldTimer=h.timers.findIndex(t=>t.ms===8000)+1;
 assert.ok(oldTimer);h.login('B');const next=api.refreshSchoolAlert(),nextTimer=h.timers.length;
 assert.equal(h.fetches.length,2);assert.ok(nextTimer>oldTimer);
 if(result==='success')old.resolve({ok:true,text:async()=>JSON.stringify([{invite_email:'a-private@example.test'}])});
 else {if(result==='timeout'){h.timers[oldTimer-1].f();assert.equal(old.options.signal.aborted,true);}const error=new Error(result);if(result==='timeout')error.name='AbortError';old.reject(error);}
 assert.equal(await p,false);assert.ok(h.clearedTimers.includes(oldTimer));assert.equal(h.timers[oldTimer-1].cancelled,true);
 assert.equal(h.clearedTimers.includes(nextTimer),false);assert.equal(h.fetches[1].options.signal.aborted,false);
 h.fetches[1].resolve({ok:true,text:async()=>JSON.stringify([])});await next;assert.ok(h.clearedTimers.includes(nextTimer));
});

for(const expression of ['schoolCompare','aiInstructor.recoveryPlan'])test('Normalized memory retains provenance: '+expression,()=>{
 const h=harness();h.eval('mdmAccountRehydrateData()');h.eval('var normalizedA='+expression+';');
 h.login('B');assert.equal(h.eval('save(SCHOOL_COMPARE_KEY,normalizedA)'),false);
});
test('Legacy School Portal uses the existing startup array normalization on account re-entry',()=>{
 const h=harness({'mdm-v1-school-portal-2::user:B':{bookings:null,requests:{legacy:true},courses:[],offers:[],reviews:[],instructors:[]}});
 h.login('B');assert.equal(h.eval('Array.isArray(schoolPortal.bookings)&&Array.isArray(schoolPortal.requests)'),true);
});
